//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersMenuControl
    {
        public string vMenuControlID { get; set; }
        public string vMenuID { get; set; }
        public int OptionID { get; set; }
    
        public virtual AspNetUsersMenu AspNetUsersMenu { get; set; }
        public virtual Option Option { get; set; }
    }
}
