//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersMenuPermission
    {
        public string vMenuPermissionID { get; set; }
        public string Id { get; set; }
        public string vMenuID { get; set; }
        public bool wEdit { get; set; }
        public bool wView { get; set; }
        public bool wAdd { get; set; }
        public bool wDelete { get; set; }
        public bool wExtract { get; set; }
        public bool wPrint { get; set; }
        public bool wDownload { get; set; }
        public bool wUpload { get; set; }
        public bool wSnyc { get; set; }
        public bool wFetch { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUsersMenu AspNetUsersMenu { get; set; }
    }
}
