//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersProfile
    {
        public string Id { get; set; }
        public string vFirstName { get; set; }
        public string vLastName { get; set; }
        public string vMiddleName { get; set; }
        public string vPhoto { get; set; }
        public string vCompany { get; set; }
        public string vPosition { get; set; }
        public string vRank { get; set; }
        public string vDepartment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
