//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersLoginHistory
    {
        public string vULHID { get; set; }
        public string Id { get; set; }
        public System.DateTime dLogIn { get; set; }
        public Nullable<System.DateTime> dLogOut { get; set; }
        public string nvIPAddress { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
