//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricMeter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectricMeter()
        {
            this.ElectricMeterDocuments = new HashSet<ElectricMeterDocument>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string ProjectCode { get; set; }
        public string UnitCategory { get; set; }
        public string UnitNos { get; set; }
        public string CustomerNos { get; set; }
        public string SalesDocNos { get; set; }
        public string QuotDocNos { get; set; }
        public Nullable<decimal> MeterDepositAmount { get; set; }
        public string ApplicationProcessStatus { get; set; }
        public Nullable<System.DateTime> DocumentaryCompletedDate { get; set; }
        public Nullable<System.DateTime> DocumentaryLastModifedDate { get; set; }
        public string DocumentaryRemarks { get; set; }
        public string RFPRushTicketNos { get; set; }
        public Nullable<System.DateTime> RFPRushTicketDate { get; set; }
        public string RFPRushTicketRemarks { get; set; }
        public Nullable<bool> IsReceivedCheck { get; set; }
        public string ReceivedCheckRemarks { get; set; }
        public Nullable<bool> WithUnpaidBills { get; set; }
        public Nullable<System.DateTime> UnpaidBillPostedDate { get; set; }
        public Nullable<bool> IsPaidSettled { get; set; }
        public Nullable<System.DateTime> PaidSettledPostedDate { get; set; }
        public string DepositApplicationRemarks { get; set; }
        public Nullable<System.DateTime> MeralcoSubmittedDate { get; set; }
        public string MeralcoSubmittedRemarks { get; set; }
        public Nullable<System.DateTime> MeralcoReceiptDate { get; set; }
        public string MeralcoReceiptRemarks { get; set; }
        public Nullable<System.DateTime> UnitOwnerReceiptDate { get; set; }
        public string UnitOwnerReceiptRemarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByPK { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedByPK { get; set; }
        public Nullable<int> UnitOwnerReceiptTAT { get; set; }
        public string UnitOwnerReceiptTATCT { get; set; }
        public Nullable<System.DateTime> ReceivedCheckDate { get; set; }
        public Nullable<int> DocCompletionTAT { get; set; }
        public string DocCompletionTATCT { get; set; }
        public Nullable<int> RFPCreationTAT { get; set; }
        public string RFPCreationTATCT { get; set; }
        public Nullable<int> CheckPaymentReleaseTAT { get; set; }
        public string CheckPaymentReleaseTATCT { get; set; }
        public Nullable<int> MeralcoSubmissionTAT { get; set; }
        public string MeralcoSubmissionTATCT { get; set; }
        public Nullable<int> TransferElectricServTAT { get; set; }
        public string TransferElectricServTATCT { get; set; }
        public string SalesElectricDocStatus { get; set; }
        public Nullable<bool> DocumentaryStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectricMeterDocument> ElectricMeterDocuments { get; set; }
    }
}
