//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessJob()
        {
            this.ProcessTitlingStatusTemps = new HashSet<ProcessTitlingStatusTemp>();
            this.ProcessElectricMeterTemps = new HashSet<ProcessElectricMeterTemp>();
        }
    
        public int Id { get; set; }
        public string StatusCode { get; set; }
        public Nullable<bool> IsSuccessStatusCode { get; set; }
        public string ReasonPhrase { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ObjectType { get; set; }
        public string ContentDetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessTitlingStatusTemp> ProcessTitlingStatusTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessElectricMeterTemp> ProcessElectricMeterTemps { get; set; }
    }
}
