//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string vSettingID { get; set; }
        public string vSettingName { get; set; }
        public string vSettingOption { get; set; }
        public string vSettingGroup { get; set; }
        public string vSettingLabel { get; set; }
    }
}
