//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameter
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.TimeSpan BusinessHourFrom { get; set; }
        public System.TimeSpan BusinessHourTo { get; set; }
        public bool Published { get; set; }
        public string Applicability { get; set; }
        public int TurnoverMaxDays { get; set; }
        public string TurnoverMaxDaysCT { get; set; }
        public int NoticeNosDays1 { get; set; }
        public bool NoticeSendRecipient1 { get; set; }
        public string NoticeRecipientEmail1 { get; set; }
        public int NoticeTemplateID1 { get; set; }
        public string NoticeCT1 { get; set; }
        public int NoticeNosDays2 { get; set; }
        public bool NoticeSendRecipient2 { get; set; }
        public string NoticeRecipientEmail2 { get; set; }
        public int NoticeTemplateID2 { get; set; }
        public string NoticeCT2 { get; set; }
        public int TurnoverMaxDays2 { get; set; }
        public string TurnoverMaxDays2CT { get; set; }
        public int ReschedMaxDays1 { get; set; }
        public string ReschedMaxDays1CT { get; set; }
        public int ReschedMaxDays2 { get; set; }
        public string ReschedMaxDays2CT { get; set; }
        public int TurnoverStatusTAT { get; set; }
        public string TurnoverStatusTATCT { get; set; }
        public int PunchlistDateTAT { get; set; }
        public string PunchlistDateTATCT { get; set; }
        public int ReinspectionDateTAT { get; set; }
        public string ReinspectionDateTATCT { get; set; }
        public int AdjReinspectionMaxDays { get; set; }
        public string AdjReinspectionMaxDaysCT { get; set; }
        public int AdjReinspectionTAT { get; set; }
        public string AdjReinspectionTATCT { get; set; }
        public int RushTicketMaxTAT { get; set; }
        public string RushTicketMaxTATCT { get; set; }
        public int UnitAcceptanceTAT { get; set; }
        public string UnitAcceptanceTATCT { get; set; }
        public int EnableTOStatusMax { get; set; }
        public string EnableTOStatusMaxCT { get; set; }
        public int DeemedDaysTAT1 { get; set; }
        public string DeemedDaysTAT1CT { get; set; }
        public int DeemedDaysTAT2 { get; set; }
        public string DeemedDaysTAT2CT { get; set; }
        public int DeemedEmailDateSentMaxDays { get; set; }
        public string DeemedEmailDateSentMaxDaysCT { get; set; }
        public bool EnableTOCutOffDate { get; set; }
        public System.DateTime TOCutOffDate { get; set; }
        public int TitleInProcessTAT1 { get; set; }
        public int TitleInProcessTAT2 { get; set; }
        public int TitleInProcessTAT3 { get; set; }
        public string TitleInProcessTATCT { get; set; }
        public int TitleTransferredTAT { get; set; }
        public string TitleTransferredTATCT { get; set; }
        public int TitleClaimedTAT { get; set; }
        public string TitleClaimedTATCT { get; set; }
        public int TaxDeclarationTransferredTAT { get; set; }
        public string TaxDeclarationTransferredTATCT { get; set; }
        public int TaxDeclarationClaimedTAT { get; set; }
        public string TaxDeclarationClaimedTATCT { get; set; }
        public int LiquidationEndorsedTAT { get; set; }
        public string LiquidationEndorsedTATCT { get; set; }
        public int TitleReleaseEndorsedTAT { get; set; }
        public string TitleReleaseEndorsedTATCT { get; set; }
        public int BuyerReleasedTAT { get; set; }
        public string BuyerReleasedTATCT { get; set; }
        public int BankReleasedTAT { get; set; }
        public string BankReleasedTATCT { get; set; }
        public System.DateTime TitlingStatusEffectivityDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByPK { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedByPK { get; set; }
        public bool EnableTSCutOffDate { get; set; }
        public System.DateTime TSCutOffDate { get; set; }
        public int UnitOwnerReceiptTAT { get; set; }
        public string UnitOwnerReceiptTATCT { get; set; }
        public System.DateTime ElectricMeterEffectivityDate { get; set; }
        public System.DateTime EMCutOffDate { get; set; }
        public int DocCompletionTAT { get; set; }
        public string DocCompletionTATCT { get; set; }
        public int RFPCreationTAT { get; set; }
        public string RFPCreationTATCT { get; set; }
        public int CheckPaymentReleaseTAT { get; set; }
        public string CheckPaymentReleaseTATCT { get; set; }
        public int MeralcoSubmissionTAT { get; set; }
        public string MeralcoSubmissionTATCT { get; set; }
        public int TransferElectricServTAT { get; set; }
        public string TransferElectricServTATCT { get; set; }
        public bool EnableEMCutOffDate { get; set; }
    }
}
