//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitlingStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TitlingStatu()
        {
            this.TitlingStatusRemarks = new HashSet<TitlingStatusRemark>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string ProjectCode { get; set; }
        public string UnitCategory { get; set; }
        public string UnitNos { get; set; }
        public string CustomerNos { get; set; }
        public string SalesDocNos { get; set; }
        public string QuotDocNos { get; set; }
        public Nullable<System.DateTime> TitleInProcessDate { get; set; }
        public Nullable<int> TitleInProcessTAT1 { get; set; }
        public Nullable<int> TitleInProcessTAT2 { get; set; }
        public Nullable<int> TitleInProcessTAT3 { get; set; }
        public string TitleInProcessTATCT { get; set; }
        public Nullable<System.DateTime> TitleTransferredDate { get; set; }
        public Nullable<int> TitleTransferredTAT { get; set; }
        public string TitleTransferredTATCT { get; set; }
        public Nullable<System.DateTime> TitleClaimedDate { get; set; }
        public Nullable<int> TitleClaimedTAT { get; set; }
        public string TitleClaimedTATCT { get; set; }
        public Nullable<System.DateTime> TaxDeclarationTransferredDate { get; set; }
        public Nullable<int> TaxDeclarationTransferredTAT { get; set; }
        public string TaxDeclarationTransferredTATCT { get; set; }
        public Nullable<System.DateTime> TaxDeclarationClaimedDate { get; set; }
        public Nullable<int> TaxDeclarationClaimedTAT { get; set; }
        public string TaxDeclarationClaimedTATCT { get; set; }
        public string TaxDecNos { get; set; }
        public Nullable<System.DateTime> LiquidationEndorsedDate { get; set; }
        public Nullable<int> LiquidationEndorsedTAT { get; set; }
        public string LiquidationEndorsedTATCT { get; set; }
        public string LiquidationRushTicketNos { get; set; }
        public string LiquidationEndorsedRemarks { get; set; }
        public Nullable<System.DateTime> TitleReleaseEndorsedDate { get; set; }
        public Nullable<int> TitleReleaseEndorsedTAT { get; set; }
        public string TitleReleaseEndorsedTATCT { get; set; }
        public string TitleReleaseRushTicketNos { get; set; }
        public string TitleReleaseEndorsedRemarks { get; set; }
        public Nullable<int> TitleLocationID { get; set; }
        public string TitleNos { get; set; }
        public string TitleRemarks { get; set; }
        public Nullable<bool> IsBankReleaseNA { get; set; }
        public Nullable<System.DateTime> BankReleasedDate { get; set; }
        public string BankReleasedRemarks { get; set; }
        public Nullable<bool> IsBuyerReleaseNA { get; set; }
        public Nullable<System.DateTime> BuyerReleasedDate { get; set; }
        public string BuyerReleasedRemarks { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByPK { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedByPK { get; set; }
    
        public virtual TitlingLocation TitlingLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TitlingStatusRemark> TitlingStatusRemarks { get; set; }
    }
}
