//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CustomerWithSO
    {
        public string SalesDocNos { get; set; }
        public string CompanyCode { get; set; }
        public string ProjectCode { get; set; }
        public string UnitNos { get; set; }
        public string RefNos { get; set; }
        public string UnitCategoryCode { get; set; }
        public string CustomerNos { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerHash { get; set; }
        public string SalesDocStatus { get; set; }
    }
}
