//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZresToExtend
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string ProjectCode { get; set; }
        public string UnitNos { get; set; }
        public string MsNos { get; set; }
        public Nullable<decimal> DeptAmnt { get; set; }
        public Nullable<System.DateTime> SupDate { get; set; }
        public Nullable<System.DateTime> RfndDate { get; set; }
        public Nullable<decimal> rfndAmt { get; set; }
        public string CustNumPark { get; set; }
        public Nullable<System.DateTime> DatPrinDate { get; set; }
        public string ParkSlotNos { get; set; }
        public string ParkingArea { get; set; }
        public Nullable<System.DateTime> ConsDelDate { get; set; }
        public Nullable<System.DateTime> LtoSaleDate { get; set; }
        public Nullable<System.DateTime> QcdAcceptDate { get; set; }
        public Nullable<System.DateTime> QcdHoverDate { get; set; }
        public Nullable<System.DateTime> ProjtoverDate { get; set; }
        public string ProjtoverTime { get; set; }
        public Nullable<System.DateTime> CmgUnitComDate { get; set; }
        public Nullable<System.DateTime> OccPermitDate { get; set; }
        public Nullable<System.DateTime> TagNoShow { get; set; }
        public Nullable<System.DateTime> LtsComDate { get; set; }
        public Nullable<System.DateTime> LtsExtDate { get; set; }
        public Nullable<System.DateTime> OomAcceptDate { get; set; }
    }
}
