//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public int Id { get; set; }
        public string vMenuID { get; set; }
        public string EventType { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public string ObjectType { get; set; }
        public string ContentDetail { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByPK { get; set; }
    
        public virtual AspNetUsersMenu AspNetUsersMenu { get; set; }
    }
}
