//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEmail
    {
        public int Id { get; set; }
        public string CustomerNos { get; set; }
        public string Adrnr { get; set; }
        public string CustomerName { get; set; }
        public string EmailAdd { get; set; }
        public string FlagDefault { get; set; }
    }
}
