//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Console.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebAppEntities : DbContext
    {
        public WebAppEntities()
            : base("name=WebAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<HttpClientLog> HttpClientLogs { get; set; }
        public virtual DbSet<UnitID_DeemedAcceptance> UnitID_DeemedAcceptance { get; set; }
        public virtual DbSet<UnitID_TOAcceptance> UnitID_TOAcceptance { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<EmailSendingQueue> EmailSendingQueues { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<AspNetUsersMenu> AspNetUsersMenus { get; set; }
    
        public virtual int spProcessBusinessRules()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spProcessBusinessRules");
        }
    
        public virtual int spProcessEmailQueueing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spProcessEmailQueueing");
        }
    }
}
