//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInventory
    {
        public int Id { get; set; }
        public string SalesDocNos { get; set; }
        public decimal SalesDocNos2 { get; set; }
        public string QuotDocNos { get; set; }
        public Nullable<System.DateTime> SalesDocDate { get; set; }
        public string SalesDocStatus { get; set; }
        public string SalesDocReason { get; set; }
        public string SalesDocItem { get; set; }
        public string CustomerNos { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerName2 { get; set; }
        public string AddrNos { get; set; }
        public string AddrStreet { get; set; }
        public string AddrHouseNos { get; set; }
        public string AddrCity { get; set; }
        public string AddrPostal { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string ProjectCode { get; set; }
        public string UnitNos { get; set; }
        public string RefNos { get; set; }
        public string Phase { get; set; }
        public string UnitType { get; set; }
        public string UnitTypeDesc { get; set; }
        public string UnitTypeCode { get; set; }
        public string UnitArea { get; set; }
        public string UnitMsrmnt { get; set; }
        public string UnitCategoryCode { get; set; }
        public string UnitCategoryDesc { get; set; }
        public string SNKS { get; set; }
        public string Intreno { get; set; }
        public Nullable<System.DateTime> TOAS { get; set; }
        public Nullable<System.DateTime> TurnoverDate { get; set; }
    }
}
