//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitID_TOAcceptance
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string ProjectCode { get; set; }
        public string UnitCategory { get; set; }
        public string UnitNos { get; set; }
        public string CustomerNos { get; set; }
        public string TurnoverStatus { get; set; }
        public System.DateTime TurnoverStatusDate { get; set; }
        public string PunchlistCategory { get; set; }
        public string PunchlistItem { get; set; }
        public Nullable<System.DateTime> PunchlistCategoryTAT { get; set; }
        public string OtherIssues { get; set; }
        public string TSRemarks { get; set; }
        public string TSAttachment { get; set; }
        public Nullable<System.DateTime> UnitAcceptanceDate { get; set; }
        public Nullable<System.DateTime> UnitAcceptanceDateTAT { get; set; }
        public Nullable<System.DateTime> KeyTransmittalDate { get; set; }
        public Nullable<System.DateTime> ReinspectionDate { get; set; }
        public Nullable<System.DateTime> ReinspectionDateTAT { get; set; }
        public Nullable<System.DateTime> AdjReinspectionDate { get; set; }
        public Nullable<System.DateTime> AdjReinspectionDateTAT { get; set; }
        public Nullable<System.DateTime> AdjReinspectionMaxDate { get; set; }
        public string RushTicketNos { get; set; }
        public Nullable<System.DateTime> RushTicketNosTAT { get; set; }
        public string SRRemarks { get; set; }
        public Nullable<System.DateTime> DeemedDateTAT1 { get; set; }
        public Nullable<System.DateTime> DeemedDateTAT2 { get; set; }
        public Nullable<int> IsUnitAcceptanceDateSAPSync { get; set; }
        public Nullable<System.DateTime> UnitAcceptanceDateSyncDate { get; set; }
        public Nullable<System.DateTime> TOAllowableDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByPK { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedByPK { get; set; }
    }
}
