//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZresCsHeader
    {
        public int Id { get; set; }
        public string SalesDocNos { get; set; }
        public decimal SalesDocNos2 { get; set; }
        public string QuotDocNos { get; set; }
        public string CustomerNos { get; set; }
        public string CompanyCode { get; set; }
        public string ProjectCode { get; set; }
        public string UnitNos { get; set; }
        public string RefNos { get; set; }
        public string UnitType { get; set; }
        public string Phase { get; set; }
        public string UnitArea { get; set; }
        public string PaymentTerm { get; set; }
        public string AccountTypeCode { get; set; }
        public string AccountTypeDesc { get; set; }
        public Nullable<decimal> TCP { get; set; }
        public Nullable<decimal> GrossPrice { get; set; }
        public Nullable<decimal> MatCost { get; set; }
        public Nullable<decimal> DiscPer1 { get; set; }
        public Nullable<decimal> DiscAmt1 { get; set; }
        public Nullable<decimal> DiscPer2 { get; set; }
        public Nullable<decimal> DiscAmt2 { get; set; }
        public Nullable<decimal> DiscPer3 { get; set; }
        public Nullable<decimal> DiscAmt3 { get; set; }
        public Nullable<decimal> DiscPer4 { get; set; }
        public Nullable<decimal> DiscAmt4 { get; set; }
        public Nullable<decimal> DiscPer5 { get; set; }
        public Nullable<decimal> DiscAmt5 { get; set; }
        public Nullable<decimal> AdjRestruct { get; set; }
        public Nullable<decimal> NetSelling { get; set; }
        public Nullable<decimal> GrossLessDisc { get; set; }
        public Nullable<decimal> VatAmnt { get; set; }
        public Nullable<decimal> NetInvestment { get; set; }
        public Nullable<decimal> ResFee { get; set; }
        public Nullable<decimal> CusBalance { get; set; }
        public string RestrucDate { get; set; }
        public Nullable<System.DateTime> ResDate { get; set; }
    }
}
